import { initializeApp } from 'https://www.gstatic.com/firebasejs/12.19.0/firebase-app.js';
import { getAuth, signInWithEmailAndPassword, signOut, getIdTokenResult } from 'https://www.gstatic.com/firebasejs/12.19.0/firebase-auth.js';
import { getDatabase, ref, push, set, get, update, query, orderByChild, equalTo } from 'https://www.gstatic.com/firebasejs/12.19.0/firebase-database.js';
import { firebaseConfig } from './firebase-config.js';

const app = initializeApp(firebaseConfig), auth = getAuth(app), db = getDatabase(app);
const menus = { meat: [['미박삼겹살','180g','13,000원'],['특목살','180g','13,000원'],['갈비본살','150g','19,000원']], side: [['미나리','','5,000원']], meal: [['공기밥','','1,000원'],['도가니된장','','3,000원'],['비빔면','','3,000원'],['물냉면','','5,000원'],['회냉면','','5,000원']], drink: [['음료','','2,000원'],['맥주','','5,000원'],['소주','','4,500원']] };
const $ = (selector) => document.querySelector(selector); let reservations = [];
const list=$('#menu-list'), nav=$('.nav'), modal=$('.booking-modal'), reserveForm=$('#reservation-form'), adminForm=$('#admin-login-form'), checkBox=$('#check-content'), title=$('#booking-title'), eyebrow=$('#modal-eyebrow'), adminPanel=$('.admin-panel'), rows=$('#reservation-rows');
checkBox.innerHTML=`<form class="reservation-form" id="reservation-check-form"><label class="field">전화번호<input name="r_tel" type="tel" required placeholder="예약 시 입력한 전화번호를 입력하세요" autocomplete="tel"></label><p class="form-note">예약 시 등록한 전화번호와 일치하는 예약만 확인할 수 있습니다.</p><p class="form-result" id="check-result" role="status"></p><button class="button dark" type="submit">예약확인</button><div class="lookup-results" id="lookup-results" aria-live="polite"></div></form>`;
function message(el,text,error=false){el.textContent=text;el.className=`form-result ${error?'error':'success'}`;} function dateText(v){return v?String(v).replace('T',' '):'-';} function stateName(v){return({r:'예약중',u:'예약사용완료',c:'예약취소'})[v]||v;}
function authErrorMessage(error){const code=error?.code||'';if(code==='auth/invalid-email')return '이메일 주소 형식이 올바르지 않습니다.';if(code==='auth/invalid-credential'||code==='auth/wrong-password'||code==='auth/user-not-found')return '관리자 아이디 또는 비밀번호가 일치하지 않습니다.';if(code==='auth/too-many-requests')return '로그인 시도가 너무 많습니다. 잠시 후 다시 시도해주세요.';if(code==='PERMISSION_DENIED'||code==='permission-denied'||/permission denied/i.test(error?.message||''))return '관리자 권한 확인이 거부되었습니다. Firebase Realtime Database Rules에 admins 경로 권한을 설정하고, 해당 관리자 UID를 admins에 등록해주세요.';return `관리자 인증 중 오류가 발생했습니다: ${error?.message||'알 수 없는 오류'}`;}
function showMenu(type){list.innerHTML=menus[type].map(([n,u,p])=>`<article><h3>${n}${u?`<small>${u}</small>`:''}</h3><strong>${p}</strong></article>`).join('');} showMenu('meat'); document.querySelectorAll('[data-menu]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-menu]').forEach(x=>x.classList.remove('active'));b.classList.add('active');showMenu(b.dataset.menu);}));
const trigger=$('.mobile-menu'); trigger.addEventListener('click',()=>{const opened=nav.classList.toggle('open');trigger.setAttribute('aria-expanded',opened);});nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');trigger.setAttribute('aria-expanded','false');}));
function openModal(type){reserveForm.hidden=type!=='reserve';adminForm.hidden=type!=='admin';checkBox.hidden=type!=='check';$('#form-result').textContent='';$('#login-result').textContent='';const data={reserve:['RESERVATION','맛있는 시간,<br><em>미리 준비할게요.</em>'],check:['RESERVATION CHECK','예약을 <em>확인</em>하세요.'],admin:['ADMIN LOGIN','관리자 <em>인증</em>']}[type];eyebrow.textContent=data[0];title.innerHTML=data[1];modal.classList.add('visible');modal.setAttribute('aria-hidden','false');}function closeModal(){modal.classList.remove('visible');modal.setAttribute('aria-hidden','true');}
document.querySelectorAll('[data-modal]').forEach(a=>a.addEventListener('click',e=>{e.preventDefault();openModal(a.dataset.modal);}));$('.modal-close').addEventListener('click',closeModal);modal.addEventListener('click',e=>{if(e.target===modal)closeModal();});
reserveForm.addEventListener('submit',async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(reserveForm));const item=push(ref(db,'reservation'));try{await set(item,{idx:item.key,r_name:data.r_name.trim(),r_date:data.r_date,rs_date:new Date().toISOString(),r_number:Number(data.r_number),r_tel:data.r_tel.trim(),r_status:'r',r_content:data.r_content.trim()});reserveForm.reset();reserveForm.r_number.value=1;message($('#form-result'),'예약 신청이 접수되었습니다. 매장에서 확인 후 연락드리겠습니다.');}catch(err){message($('#form-result'),`예약 저장에 실패했습니다: ${err.message}`,true);}});
$('#reservation-check-form').addEventListener('submit',async e=>{e.preventDefault();const out=$('#lookup-results'),result=$('#check-result'),phone=new FormData(e.currentTarget).get('r_tel').trim();out.innerHTML='';try{const snap=await get(query(ref(db,'reservation'),orderByChild('r_tel'),equalTo(phone)));const matches=Object.entries(snap.val()||{}).map(([id,v])=>({id,...v})).sort((a,b)=>(a.r_date||'').localeCompare(b.r_date||''));message(result,matches.length?`${matches.length}건의 예약을 찾았습니다.`:'일치하는 예약 정보가 없습니다.');out.innerHTML=matches.map(x=>`<article class="lookup-card"><p><b>예약자</b>${x.r_name}</p><p><b>방문일시</b>${dateText(x.r_date)}</p><p><b>방문인원</b>${x.r_number}명</p><p><b>예약상태</b>${stateName(x.r_status)}</p><p><b>참고사항</b>${x.r_content||'-'}</p></article>`).join('');}catch(err){message(result,`예약 확인에 실패했습니다: ${err.message}`,true);}});
async function isAdmin(user){const token=await getIdTokenResult(user,true);return token.claims.admin===true||(await get(ref(db,`admins/${user.uid}`))).exists();}
adminForm.addEventListener('submit',async e=>{e.preventDefault();const data=new FormData(adminForm);try{const credential=await signInWithEmailAndPassword(auth,data.get('email'),data.get('password'));if(!await isAdmin(credential.user)){await signOut(auth);throw new Error('관리자 권한이 없는 계정입니다. Firebase Realtime Database의 admins/{관리자 UID} 경로에 관리자 등록이 필요합니다.');}closeModal();adminPanel.classList.add('visible');$('#admin-info').scrollIntoView({behavior:'smooth'});await loadReservations();}catch(err){message($('#login-result'),authErrorMessage(err),true);}});
async function loadReservations(){$('#admin-message').textContent='예약 정보를 불러오는 중입니다.';try{const snap=await get(ref(db,'reservation')),now=new Date();reservations=Object.entries(snap.val()||{}).map(([id,v])=>({id,...v})).sort((a,b)=>{const ad=new Date(a.r_date),bd=new Date(b.r_date);if((ad>=now)!==(bd>=now))return ad>=now?-1:1;return ad-bd;});$('#admin-message').textContent=`총 ${reservations.length}건의 예약 정보입니다.`;renderReservations();}catch(err){$('#admin-message').textContent=`조회에 실패했습니다: ${err.message}`;}}
function renderReservations(){const field=$('#search-field').value,key=$('#search-keyword').value.trim().toLowerCase(),state=$('#status-filter').value;const filtered=reservations.filter(x=>(state==='all'||x.r_status===state)&&(!key||String(x[field]||'').toLowerCase().includes(key)));rows.innerHTML=filtered.length?filtered.map(x=>`<tr><td>${x.idx||x.id}</td><td>${x.r_name||'-'}</td><td>${dateText(x.r_date)}</td><td>${dateText(x.rs_date)}</td><td>${x.r_number||0}명</td><td>${x.r_tel||'-'}</td><td>${x.r_content||'-'}</td><td><select class="status-select" data-id="${x.id}" data-current="${x.r_status}"><option value="r" ${x.r_status==='r'?'selected':''}>예약중</option><option value="u" ${x.r_status==='u'?'selected':''}>예약사용완료</option><option value="c" ${x.r_status==='c'?'selected':''}>예약취소</option></select></td></tr>`).join(''):'<tr><td class="empty-row" colspan="8">조건에 맞는 예약 정보가 없습니다.</td></tr>';rows.querySelectorAll('.status-select').forEach(s=>s.addEventListener('change',updateStatus));}
async function updateStatus(e){const s=e.target,current=s.dataset.current,next=s.value;if(current==='r'&&(next==='u'||next==='c')&&!confirm(`예약 상태를 '${stateName(next)}'로 변경하시겠습니까?`)){s.value=current;return;}try{await update(ref(db,`reservation/${s.dataset.id}`),{r_status:next});const item=reservations.find(x=>x.id===s.dataset.id);item.r_status=next;s.dataset.current=next;}catch(err){s.value=current;alert(`상태 변경에 실패했습니다: ${err.message}`);}}
['#search-field','#search-keyword','#status-filter'].forEach(s=>$(s).addEventListener(s==='#search-keyword'?'input':'change',renderReservations));$('#logout-button').addEventListener('click',async()=>{await signOut(auth);adminPanel.classList.remove('visible');$('#home').scrollIntoView({behavior:'smooth'});});const home=$('.home-button');function toggleHome(){home.classList.toggle('visible',scrollY>260);}addEventListener('scroll',toggleHome,{passive:true});toggleHome();
